# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='course',
        ),
    ]
