# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmenu', '0002_remove_product_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shopqty',
            new_name='qty',
        ),
    ]
